# Generated by Django 4.2 on 2023-04-23 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abstergo_app', '0002_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_mod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
