# Generated by Django 4.2 on 2023-04-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstergo_app', '0003_product_last_mod_alter_product_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_mod',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
