# Generated by Django 4.2 on 2023-04-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstergo_app', '0004_remove_product_last_mod_alter_product_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
